const http=require('node:http'); const fs=require('node:fs'); const path=require('node:path'); const {URL}=require('node:url'); const {DatabaseSync}=require('node:sqlite');
const PORT=process.env.PORT||3000; const DBPATH=process.env.DATABASE_PATH||path.join(__dirname,'data','revolt-fleet.db'); fs.mkdirSync(path.dirname(DBPATH),{recursive:true});
const db=new DatabaseSync(DBPATH); db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS vehicles(id TEXT PRIMARY KEY,reg TEXT UNIQUE,name TEXT,year INTEGER,driver TEXT,dept TEXT,state TEXT,speed REAL DEFAULT 0,mileage REAL DEFAULT 0,fuel TEXT,lat REAL,lng REAL,last TEXT,service TEXT,insurance TEXT,tracker_id TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS drivers(id TEXT PRIMARY KEY,name TEXT,phone TEXT,lic TEXT,expiry TEXT,vehicle TEXT,score INTEGER,status TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS trips(id TEXT PRIMARY KEY,vehicle TEXT,driver TEXT,origin TEXT,destination TEXT,start TEXT,status TEXT,distance TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS maintenance(id INTEGER PRIMARY KEY AUTOINCREMENT,vehicle TEXT,service TEXT,due_date TEXT,due_in TEXT,status TEXT,cost TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS fuel(id INTEGER PRIMARY KEY AUTOINCREMENT,date TEXT,vehicle TEXT,driver TEXT,litres TEXT,amount TEXT,station TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS incidents(id TEXT PRIMARY KEY,vehicle TEXT,type TEXT,datetime TEXT,status TEXT,location TEXT,description TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS documents(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,category TEXT,type TEXT,updated TEXT);
CREATE TABLE IF NOT EXISTS alerts(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT,message TEXT,ago TEXT,severity TEXT,status TEXT DEFAULT 'New',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,email TEXT UNIQUE,role TEXT,status TEXT);
CREATE TABLE IF NOT EXISTS gps_history(id INTEGER PRIMARY KEY AUTOINCREMENT,vehicle TEXT,lat REAL,lng REAL,speed REAL,recorded_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS audit_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,actor TEXT,action TEXT,entity TEXT,entity_id TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
function count(t){return db.prepare(`SELECT COUNT(*) n FROM ${t}`).get().n} function ins(sql,rows){let s=db.prepare(sql);db.exec('BEGIN');try{for(let r of rows)s.run(...r);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}
if(!count('vehicles')){let names=['Toyota Hilux','Toyota Prado','Ford Ranger','Nissan Patrol','Mitsubishi L200','Toyota Corolla','Isuzu D-Max','Toyota Hiace','Kia Sportage','Hyundai Tucson','Toyota Land Cruiser','Ford Everest','Nissan Navara','Honda CR-V','Toyota Fortuner','Mercedes Sprinter','Kia Sorento','Hyundai Santa Fe','Toyota RAV4','Isuzu NQR']; let drivers=['Kofi Mensah','Ama Boateng','Kwame Mensah','Daniel Adjei','Emmanuel Asare','Unassigned','Akosua Owusu','Samuel Tetteh','Grace Ofori','Yaw Antwi','Linda Aidoo','Michael Quaye','Nana Serwaa','Joseph Badu','Esi Hammond','Unassigned','Richard Kumi','Mabel Annan','Kojo Nyarko','Ibrahim Sule']; let depts=['Operations','Executive','Field Services','Security','Projects','Administration','Operations','Staff Transport','Finance','ICT','Executive','Projects','Logistics','HR','Operations','Staff Transport','Sales','Procurement','Administration','Logistics']; let states=['Moving','Parked','Moving','Parked','Moving','Offline','Moving','Parked','Moving','Parked','Moving','Moving','Parked','Offline','Moving','Parked','Moving','Parked','Moving','Parked']; let coords=[[5.6037,-.187],[5.6201,-.1732],[5.6372,-.1699],[5.5738,-.2012],[5.6698,-.1634],[5.5602,-.2057],[5.5911,-.226],[5.6508,-.2184],[5.614,-.201],[5.646,-.154],[5.589,-.182],[5.632,-.213],[5.681,-.178],[5.572,-.171],[5.606,-.232],[5.625,-.194],[5.657,-.187],[5.598,-.157],[5.617,-.219],[5.676,-.205]]; let rows=names.map((n,i)=>[`RVT-${String([102,88,15,21,33,41,57,69,74,81,93,108,116,124,131,142,151,163,174,188][i]).padStart(3,'0')}`,`G${['T','N','W','R','T','E'][i%6]} ${String(1500+i*317).slice(-4)}-${21+i%5}`,n,2019+i%6,drivers[i],depts[i],states[i],states[i]=='Moving'?35+(i*7)%55:0,22000+i*6100,i%7===5?'Petrol':'Diesel',coords[i][0],coords[i][1],states[i]=='Offline'?'Yesterday 16:45':'Now',i%5===0?'Overdue':`${16+i%12} Sep 2026`,`${8+i%20} ${i%2?'Nov':'Dec'} 2026`,`GPS-${1000+i}`]); ins('INSERT INTO vehicles(id,reg,name,year,driver,dept,state,speed,mileage,fuel,lat,lng,last,service,insurance,tracker_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',rows)}
if(!count('drivers')){let ns=['Kofi Mensah','Ama Boateng','Kwame Mensah','Daniel Adjei','Emmanuel Asare','Akosua Owusu','Samuel Tetteh','Grace Ofori','Yaw Antwi','Linda Aidoo','Michael Quaye','Nana Serwaa','Joseph Badu','Esi Hammond','Richard Kumi']; let vs=db.prepare("SELECT id FROM vehicles WHERE driver!='Unassigned' LIMIT 15").all(); ins('INSERT INTO drivers(id,name,phone,lic,expiry,vehicle,score,status) VALUES(?,?,?,?,?,?,?,?)',ns.map((n,i)=>[`DRV-${String(i+1).padStart(3,'0')}`,n,`02${i%8} 55${i} ${String(1880+i*137).slice(-4)}`,i%4===3?'D':'C',`${18+i%10} ${i%2?'Mar':'Nov'} 2027`,vs[i]?.id||'Unassigned',78+(i*7)%21,i===4?'Review':'Active']))}
if(!count('trips')) ins('INSERT INTO trips(id,vehicle,driver,origin,destination,start,status,distance) VALUES(?,?,?,?,?,?,?,?)',Array.from({length:18},(_,i)=>[`TRP-260914-${String(18-i).padStart(2,'0')}`,db.prepare('SELECT id FROM vehicles LIMIT 1 OFFSET ?').get(i%20).id,db.prepare('SELECT name FROM drivers LIMIT 1 OFFSET ?').get(i%15).name,['Head Office','Airport','Spintex','East Legon'][i%4],['Tema Port','Adenta','Labadi','Osu'][i%4],`${String(7+i%5).padStart(2,'0')}:${i%2?'45':'15'}`,i<5?'Active':'Completed',`${17+i*2.3.toFixed?.(1)||17} km`]));
if(!count('maintenance')) ins('INSERT INTO maintenance(vehicle,service,due_date,due_in,status,cost) VALUES(?,?,?,?,?,?)',Array.from({length:12},(_,i)=>[db.prepare('SELECT id FROM vehicles LIMIT 1 OFFSET ?').get(i).id,['10,000 km Service','Oil & Filter Change','Brake Inspection','Tyre Rotation'][i%4],`${16+i} Sep 2026`,i===2?'Overdue':`${5+i} days`,i===2?'Overdue':'Upcoming',`GHS ${450+i*175}`]));
if(!count('fuel')) ins('INSERT INTO fuel(date,vehicle,driver,litres,amount,station) VALUES(?,?,?,?,?,?)',Array.from({length:25},(_,i)=>[`${14-i%10} Sep 2026`,db.prepare('SELECT id FROM vehicles LIMIT 1 OFFSET ?').get(i%20).id,db.prepare('SELECT name FROM drivers LIMIT 1 OFFSET ?').get(i%15).name,`${35+i%31} L`,`GHS ${(525+(i%31)*15).toFixed(2)}`,['Total, Tema','Shell, Accra','Puma, Spintex','GOIL, Airport'][i%4]]));
if(!count('incidents')) ins('INSERT INTO incidents(id,vehicle,type,datetime,status,location,description) VALUES(?,?,?,?,?,?,?)',[['INC-0926-004','RVT-033','Speeding','14 Sep 2026 07:12','Open','N1 Highway','Speed threshold exceeded'],['INC-0926-003','RVT-021','Minor body damage','12 Sep 2026 18:40','Under Review','Airport Area','Parking damage'],['INC-0926-002','RVT-041','Battery failure','10 Sep 2026 09:05','Resolved','Head Office','Battery replaced'],['INC-0926-001','RVT-102','Tyre puncture','08 Sep 2026 13:25','Resolved','Tema Motorway','Tyre changed']]);
if(!count('documents')) ins('INSERT INTO documents(name,category,type,updated) VALUES(?,?,?,?)',[['Fleet Insurance Schedule','Insurance','PDF','Updated 10 Sep 2026'],['Vehicle Registration Register','Compliance','XLSX','Updated 08 Sep 2026'],['Driver Licence Register','Drivers','XLSX','Updated 12 Sep 2026'],['Roadworthiness Certificates','Compliance','ZIP','Updated 01 Sep 2026'],['Fleet Operations Policy','Policy','PDF','Updated 15 Aug 2026'],['Accident Reporting Procedure','Policy','PDF','Updated 22 Aug 2026']]);
if(!count('alerts')) ins('INSERT INTO alerts(title,message,ago,severity,status) VALUES(?,?,?,?,?)',[['Maintenance Due','RVT-015 is due for service','10 min ago','amber','New'],['Geofence Alert','RVT-102 left the Accra operating zone','25 min ago','red','New'],['Insurance Expiry','RVT-069 insurance expires in 7 days','1 hour ago','red','New'],['Driver Licence','Samuel Tetteh licence expires soon','2 hours ago','amber','Read'],['GPS Reconnected','RVT-057 tracker is back online','3 hours ago','green','Read']]);
if(!count('users')) ins('INSERT INTO users(name,email,role,status) VALUES(?,?,?,?)',[['Fleet Manager','fleet.manager@revolt.local','Administrator','Active'],['Ama Owusu','ama.owusu@revolt.local','Finance Officer','Active'],['Kojo Addo','kojo.addo@revolt.local','Operations Manager','Active'],['Nana Yeboah','nana.yeboah@revolt.local','Department Manager','Active']]);
function json(res,code,data){res.writeHead(code,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify(data))} function body(req){return new Promise((ok,no)=>{let d='';req.on('data',c=>d+=c);req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch(e){no(e)}})})}
const maps={vehicles:'vehicles',drivers:'drivers',trips:'trips',maintenance:'maintenance',fuel:'fuel',incidents:'incidents',documents:'documents',alerts:'alerts',users:'users'};
async function api(req,res,u){let p=u.pathname.split('/').filter(Boolean); if(p[1]==='health'&&req.method==='GET') return json(res,200,{status:'ok',service:'revolt-corporate-fleet',database:DBPATH,time:new Date().toISOString()}); if(p[1]==='bootstrap'&&req.method==='GET'){let out={};for(let [k,t] of Object.entries(maps))out[k]=db.prepare(`SELECT * FROM ${t} ORDER BY rowid DESC`).all();return json(res,200,out)} if(p[1]==='gps'&&p[2]==='ingest'&&req.method==='POST'){let x=await body(req);let v=db.prepare('SELECT * FROM vehicles WHERE id=? OR tracker_id=?').get(x.vehicle||null,x.tracker_id||null);if(!v)return json(res,404,{error:'Vehicle/tracker not found'});db.prepare("UPDATE vehicles SET lat=?,lng=?,speed=?,state=?,last='Now' WHERE id=?").run(+x.lat,+x.lng,+x.speed||0,(+x.speed||0)>2?'Moving':'Parked',v.id);db.prepare('INSERT INTO gps_history(vehicle,lat,lng,speed) VALUES(?,?,?,?)').run(v.id,+x.lat,+x.lng,+x.speed||0);return json(res,200,{ok:true,vehicle:v.id})} if(p[1]==='gps'&&p[2]==='history'&&req.method==='GET'){return json(res,200,db.prepare('SELECT * FROM gps_history WHERE vehicle=? ORDER BY id DESC LIMIT 500').all(u.searchParams.get('vehicle')))} let key=p[1],table=maps[key]; if(!table)return json(res,404,{error:'API endpoint not found'}); if(req.method==='GET')return json(res,200,db.prepare(`SELECT * FROM ${table} ORDER BY rowid DESC`).all()); if(req.method==='POST'){let x=await body(req);let id;if(key==='vehicles'){db.prepare('INSERT INTO vehicles(id,reg,name,year,driver,dept,state,speed,mileage,fuel,lat,lng,last,service,insurance,tracker_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(x.id,x.reg,x.name,+x.year,x.driver||'Unassigned',x.dept||'Operations','Parked',0,+x.mileage||0,x.fuel||'Diesel',+x.lat||5.6037,+x.lng||-.187,'Just added','Not scheduled','Not recorded',x.tracker_id||`GPS-${Date.now()}`);id=x.id}else if(key==='drivers'){id=x.id||`DRV-${String(count('drivers')+1).padStart(3,'0')}`;db.prepare('INSERT INTO drivers(id,name,phone,lic,expiry,vehicle,score,status) VALUES(?,?,?,?,?,?,?,?)').run(id,x.name,x.phone,x.lic||'C',x.expiry||'',x.vehicle||'Unassigned',100,'Active')}else if(key==='fuel'){db.prepare('INSERT INTO fuel(date,vehicle,driver,litres,amount,station) VALUES(?,?,?,?,?,?)').run(x.date||new Date().toLocaleDateString('en-GB'),x.vehicle,x.driver||'',x.litres,x.amount,x.station);id=Number(db.prepare('SELECT last_insert_rowid() id').get().id)}else if(key==='incidents'){id=x.id||`INC-${Date.now()}`;db.prepare('INSERT INTO incidents(id,vehicle,type,datetime,status,location,description) VALUES(?,?,?,?,?,?,?)').run(id,x.vehicle,x.type,new Date().toLocaleString(),'Open',x.location,x.description||'')}else return json(res,400,{error:'Create not enabled for this resource'});db.prepare('INSERT INTO audit_logs(actor,action,entity,entity_id) VALUES(?,?,?,?)').run('Fleet Manager','CREATE',key,String(id));return json(res,201,{ok:true,id})} json(res,405,{error:'Method not allowed'})}
function staticFile(req,res,u){let rel=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname.slice(1));let f=path.join(__dirname,'public',rel);if(!f.startsWith(path.join(__dirname,'public'))||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('Not found')}let ext=path.extname(f),types={'.html':'text/html','.js':'application/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(f).pipe(res)}
http.createServer(async(req,res)=>{try{let u=new URL(req.url,`http://${req.headers.host}`);if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS'});return res.end()}if(u.pathname.startsWith('/api/'))return await api(req,res,u);staticFile(req,res,u)}catch(e){console.error(e);json(res,500,{error:e.message})}}).listen(PORT,()=>console.log(`Revolt Fleet running on http://localhost:${PORT} | DB ${DBPATH}`));
